name: Create iOS simulator
description: Create simulator to be used for a test run
runs:
  using: composite
  steps:
    - name: Gem Cache
      uses: actions/cache@v4
      id: dependencies_cache
      with:
        path: |
          vendor
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
            ${{ runner.os }}-gems-
